# Generated by Django 5.0.1 on 2024-03-14 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_photocomment_user_photolike_user'),
        ('photos', '0002_petphoto_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='modified_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='pet_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.petphoto'),
        ),
    ]
